CREATE TABLE "FRECUENCIAS" (
	"COOPERATIVA"	TEXT,
	"DESTINO"	TEXT,
	"HORA"	TEXT,
	"JORNADA" 	TEXT,
	PRIMARY KEY("COOPERATIVA","DESTINO","HORA")
);

CREATE TABLE "USUARIOS" (
	"CEDULA"	TEXT,
	"NOMBRE"	TEXT NOT NULL,
	"NUMERO_CELULAR"	TEXT,
	"CONTRASEÑA"	TEXT,
	"ROL"	TEXT,
	PRIMARY KEY("CEDULA")
);

CREATE TABLE "REGISTRO" (
	"COOPERATIVA"	TEXT,
	"USUARIO"	TEXT,
	"DESTINO"	TEXT,
	"HORA"	TEXT,
	"FECHA"	TEXT NOT NULL,
	"FRECUENCIA"	TEXT,
	"NUM_PASAJEROS"	INTEGER,
	"TIPO_FREC"	TEXT,
	"VALOR" 	INTEGER,
	"NUM_TICKET"	TEXT,
	PRIMARY KEY("COOPERATIVA","HORA","FECHA","USUARIO", "NUM_TICKET"),
	FOREIGN KEY("COOPERATIVA", "DESTINO", "HORA") REFERENCES "FRECUENCIAS"("COOPERATIVA", "DESTINO", "HORA"),
	FOREIGN KEY("USUARIO") REFERENCES "USUARIOS"("CEDULA")
);

CREATE TABLE "REGISTRO_EXTRA" (
	"COOPERATIVA"	TEXT,
	"USUARIO"	TEXT,
	"DESTINO"	TEXT,
	"HORA"	TEXT,
	"FECHA"	TEXT NOT NULL,
	"FRECUENCIA"	TEXT,
	"NUM_PASAJEROS"	INTEGER,
	"TIPO_FREC"	TEXT,
	"VALOR" 	INTEGER,
	"NUM_TICKET"	TEXT,
	PRIMARY KEY("COOPERATIVA","HORA","FECHA","USUARIO", "NUM_TICKET"),
	FOREIGN KEY("USUARIO") REFERENCES "USUARIOS"("CEDULA")
);


INSERT INTO "USUARIOS" ("CEDULA", "NOMBRE", "NUMERO_CELULAR", "CONTRASEÑA", "ROL") 
VALUES
("0605888221","Joel Inca","098 305 4758","admin","usuario"),
("0604844324","Cristina Huisha","098 305 4758","admin","administrador");

INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('2 DE OCTUBRE', 'SAN JUAN-LA DELICIA', '06H30', 'MAÑANA');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('2 DE OCTUBRE', 'SHOBOL', '06H40', 'MAÑANA');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('2 DE OCTUBRE', 'SAN JUAN-POLVORIN', '06H50', 'MAÑANA');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('2 DE OCTUBRE', 'SAN JUAN - POLVORIN', '07H15', 'MAÑANA');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('2 DE OCTUBRE', 'U.E. CHIMBORAZO', '07H45', 'MAÑANA');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('2 DE OCTUBRE', 'POLVORIN', '08H15', 'MAÑANA');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('2 DE OCTUBRE', 'SHOBOL', '08H45', 'MAÑANA');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('2 DE OCTUBRE', 'SAN JUAN - LA DELICIA', '09H15', 'MAÑANA');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('2 DE OCTUBRE', 'SHOBOL', '09H45', 'MAÑANA');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('2 DE OCTUBRE', 'POLVORIN', '10H15', 'MAÑANA');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('2 DE OCTUBRE', 'POLVORIN', '10H45', 'MAÑANA');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('2 DE OCTUBRE', 'POLVORIN', '11H15', 'MAÑANA');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('2 DE OCTUBRE', 'POLVORIN', '11H45', 'MAÑANA');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('2 DE OCTUBRE', 'POLVORIN', '12H15', 'MAÑANA');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('2 DE OCTUBRE', 'POLVORIN', '12H45', 'MAÑANA');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('2 DE OCTUBRE', 'POLVORIN', '13H10', 'TARDE');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('2 DE OCTUBRE', 'POLVORIN', '13H30', 'TARDE');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('2 DE OCTUBRE', 'POLVORIN', '13H50', 'TARDE');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('2 DE OCTUBRE', 'POLVORIN', '14H15', 'TARDE');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('2 DE OCTUBRE', 'POLVORIN', '14H45', 'TARDE');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('2 DE OCTUBRE', 'POLVORIN', '15H15', 'TARDE');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('2 DE OCTUBRE', 'POLVORIN', '15H45', 'TARDE');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('2 DE OCTUBRE', 'POLVORIN', '16H15', 'TARDE');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('2 DE OCTUBRE', 'POLVORIN', '16H45', 'TARDE');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('2 DE OCTUBRE', 'POLVORIN', '17H15', 'TARDE');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('2 DE OCTUBRE', 'POLVORIN', '17H45', 'TARDE');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('2 DE OCTUBRE', 'POLVORIN', '18H15', 'TARDE');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('2 DE OCTUBRE', 'POLVORIN', '18H45', 'TARDE');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('2 DE OCTUBRE', 'POLVORIN', '19H15', 'TARDE');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('2 DE OCTUBRE', 'POLVORIN', '19H45', 'TARDE');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('2 DE OCTUBRE', 'POLVORIN', '20H15', 'TARDE');

INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('ALIANZA SAN JUAN', 'GALLO RUMI', '06H30', 'MAÑANA');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('ALIANZA SAN JUAN', 'LA CALERA', '06H35', 'MAÑANA');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('ALIANZA SAN JUAN', 'LA CALERA', '06H45', 'MAÑANA');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('ALIANZA SAN JUAN', 'SAN JUAN - LA CALERA', '07H00', 'MAÑANA');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('ALIANZA SAN JUAN', 'SAN JUAN - LA CALERA', '07H30', 'MAÑANA');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('ALIANZA SAN JUAN', 'SAN JUAN - LA CALERA', '08H00', 'MAÑANA');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('ALIANZA SAN JUAN', 'LA CALERA', '08H30', 'MAÑANA');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('ALIANZA SAN JUAN', 'LA CALERA', '09H00', 'MAÑANA');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('ALIANZA SAN JUAN', 'LA CALERA', '09H30', 'MAÑANA');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('ALIANZA SAN JUAN', 'SAN JUAN - LA CALERA', '10H00', 'MAÑANA');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('ALIANZA SAN JUAN', 'SAN JUAN - LA CALERA', '10H30', 'MAÑANA');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('ALIANZA SAN JUAN', 'SAN JUAN - LA CALERA', '11H00', 'MAÑANA');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('ALIANZA SAN JUAN', 'LA CALERA', '11H30', 'MAÑANA');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('ALIANZA SAN JUAN', 'SAN JUAN - LA CALERA', '12H00', 'MAÑANA');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('ALIANZA SAN JUAN', 'SAN JUAN - LA CALERA', '12H30', 'MAÑANA');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('ALIANZA SAN JUAN', 'SAN JUAN - LA CALERA', '13H00', 'MAÑANA');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('ALIANZA SAN JUAN', 'LA CALERA', '13H20', 'TARDE');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('ALIANZA SAN JUAN', 'SAN JUAN - LA CALERA', '13H40', 'TARDE');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('ALIANZA SAN JUAN', 'SAN JUAN - LA CALERA', '14H00', 'TARDE');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('ALIANZA SAN JUAN', 'SAN JUAN - LA CALERA', '14H30', 'TARDE');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('ALIANZA SAN JUAN', 'SAN JUAN - LA CALERA', '15H00', 'TARDE');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('ALIANZA SAN JUAN', 'SAN JUAN - LA CALERA', '15H30', 'TARDE');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('ALIANZA SAN JUAN', 'SAN JUAN - LA CALERA', '16H00', 'TARDE');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('ALIANZA SAN JUAN', 'SAN JUAN - LA CALERA', '16H30', 'TARDE');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('ALIANZA SAN JUAN', 'SAN JUAN - LA CALERA', '17H00', 'TARDE');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('ALIANZA SAN JUAN', 'SAN JUAN - LA CALERA', '17H30', 'TARDE');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('ALIANZA SAN JUAN', 'SAN JUAN - LA CALERA', '18H00', 'TARDE');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('ALIANZA SAN JUAN', 'SAN JUAN - LA CALERA', '18H30', 'TARDE');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('ALIANZA SAN JUAN', 'SAN JUAN - LA CALERA', '19H00', 'TARDE');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('ALIANZA SAN JUAN', 'SAN JUAN - LA CALERA', '19H30', 'TARDE');
INSERT INTO FRECUENCIAS (COOPERATIVA, DESTINO, HORA, JORNADA) VALUES ('ALIANZA SAN JUAN', 'LA CALERA', '20H00', 'TARDE');

INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('13H30', 'CAMPESINOS UNIDOS', 'CALPILOMA', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('13H30', 'CAMPESINOS UNIDOS', 'LA MOYA-JATARI-RUMICRUZ', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('13H30', 'CAMPESINOS UNIDOS', 'PALACIO REAL', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('14H00', 'CAMPESINOS UNIDOS', 'CHIQUICAZ', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('14H10', 'CAMPESINOS UNIDOS', 'LA MOYA-JATARI-RUMICRUZ', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('15H00', 'CAMPESINOS UNIDOS', 'CUNDUANA-GAUSHI CHICO', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('15H00', 'CAMPESINOS UNIDOS', 'NITILUISA', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('15H00', 'CAMPESINOS UNIDOS', 'SAN FRANCISCO DE CUNUGUACHAY', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('16H00', 'CAMPESINOS UNIDOS', 'LA MOYA-JATARI-RUMICRUZ', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('16H00', 'CAMPESINOS UNIDOS', 'NITILUISA', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('16H30', 'CAMPESINOS UNIDOS', 'LA MOYA-JATARI-RUMICRUZ', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('17H00', 'CAMPESINOS UNIDOS', 'NITILUISA', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('17H00', 'CAMPESINOS UNIDOS', 'SAN FRANCISCO DE CUNUGUACHAY', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('17H30', 'CAMPESINOS UNIDOS', 'LA MOYA-JATARI-RUMICRUZ', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('17H30', 'CAMPESINOS UNIDOS', 'PALACIO REAL', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('18H00', 'CAMPESINOS UNIDOS', 'CALPILOMA', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('18H00', 'CAMPESINOS UNIDOS', 'CUNDUANA-GAUSHI CHICO', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('18H00', 'CAMPESINOS UNIDOS', 'LA MOYA-JATARI-RUMICRUZ', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('18H00', 'CAMPESINOS UNIDOS', 'NITILUISA', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('18H30', 'CAMPESINOS UNIDOS', 'CHIQUICAZ', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('18H30', 'CAMPESINOS UNIDOS', 'LA MOYA-JATARI-RUMICRUZ', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('18H45', 'CAMPESINOS UNIDOS', 'LA MOYA-JATARI-RUMICRUZ', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('19H00', 'CAMPESINOS UNIDOS', 'LA MOYA-JATARI-RUMICRUZ', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('19H00', 'CAMPESINOS UNIDOS', 'NITILUISA', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('19H15', 'CAMPESINOS UNIDOS', 'LA MOYA-JATARI-RUMICRUZ', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('19H25', 'CAMPESINOS UNIDOS', 'LA MOYA-JATARI-RUMICRUZ', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('06H45', 'CAMPESINOS UNIDOS', 'LA MOYA-JATARI-RUMICRUZ', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('07H00', 'CAMPESINOS UNIDOS', 'CHIQUICAZ', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('07H00', 'CAMPESINOS UNIDOS', 'CUNDUANA-GAUSHI CHICO', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('07H00', 'CAMPESINOS UNIDOS', 'LA MOYA-JATARI-RUMICRUZ', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('07H00', 'CAMPESINOS UNIDOS', 'NITILUISA', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('07H00', 'CAMPESINOS UNIDOS', 'SAN FRANCISCO DE CUNUGUACHAY', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('07H15', 'CAMPESINOS UNIDOS', 'LA MOYA-JATARI-RUMICRUZ', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('07H30', 'CAMPESINOS UNIDOS', 'CALPILOMA', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('07H30', 'CAMPESINOS UNIDOS', 'LA MOYA-JATARI-RUMICRUZ', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('07H30', 'CAMPESINOS UNIDOS', 'PALACIO REAL', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('07H30', 'CAMPESINOS UNIDOS', 'SAN FRANCISCO DE CUNUGUACHAY', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('08H00', 'CAMPESINOS UNIDOS', 'LA MOYA-JATARI-RUMICRUZ', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('08H00', 'CAMPESINOS UNIDOS', 'NITILUISA', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('09H00', 'CAMPESINOS UNIDOS', 'LA MOYA-JATARI-RUMICRUZ', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('10H00', 'CAMPESINOS UNIDOS', 'LA MOYA-JATARI-RUMICRUZ', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('10H35', 'CAMPESINOS UNIDOS', 'LA MOYA-JATARI-RUMICRUZ', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('11H00', 'CAMPESINOS UNIDOS', 'CALPILOMA', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('11H00', 'CAMPESINOS UNIDOS', 'CHIQUICAZ', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('11H00', 'CAMPESINOS UNIDOS', 'LA MOYA-JATARI-RUMICRUZ', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('11H00', 'CAMPESINOS UNIDOS', 'PALACIO REAL', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('11H00', 'CAMPESINOS UNIDOS', 'SAN FRANCISCO DE CUNUGUACHAY', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('11H30', 'CAMPESINOS UNIDOS', 'NITILUISA', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('12H00', 'CAMPESINOS UNIDOS', 'CUNDUANA-GAUSHI CHICO', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('12H00', 'CAMPESINOS UNIDOS', 'LA MOYA-JATARI-RUMICRUZ', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('12H30', 'CAMPESINOS UNIDOS', 'NITILUISA', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('12H30', 'CAMPESINOS UNIDOS', 'SAN FRANCISCO DE CUNUGUACHAY', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('13H00', 'CAMPESINOS UNIDOS', 'LA MOYA-JATARI-RUMICRUZ', 'MAÑANA');

INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('06H20', 'CONDOR', 'SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('06H30', 'CONDOR', 'PULINGUI-SILVERIA', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('06H30', 'CONDOR', 'SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('06H40', 'CONDOR', 'SANJAPAMBA', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('06H45', 'CONDOR', 'SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('06H50', 'CONDOR', 'BATZACON', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('06H50', 'CONDOR', 'PULINGUI-SILVERIA', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('07H00', 'CONDOR', 'BATZACON', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('07H00', 'CONDOR', 'SANTA LUCIA', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('07H00', 'CONDOR', 'SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('07H00', 'CONDOR', 'UCHANCHI', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('07H30', 'CONDOR', 'PULINGUI-SILVERIA', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('07H30', 'CONDOR', 'SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('08H10', 'CONDOR', 'SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('08H30', 'CONDOR', 'PULINGUI-SILVERIA', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('08H50', 'CONDOR', 'SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('09H30', 'CONDOR', 'PULINGUI-SILVERIA', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('09H30', 'CONDOR', 'SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('10H10', 'CONDOR', 'SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('10H15', 'CONDOR', 'SANJAPAMBA', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('10H50', 'CONDOR', 'SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('11H00', 'CONDOR', 'SANTA LUCIA', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('11H20', 'CONDOR', 'SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('11H45', 'CONDOR', 'PULINGUI-SILVERIA', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('11H50', 'CONDOR', 'SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('12H10', 'CONDOR', 'UCHANCHI', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('12H20', 'CONDOR', 'SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('12H30', 'CONDOR', 'PULINGUI-SILVERIA', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('12H50', 'CONDOR', 'SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('13H00', 'CONDOR', 'BATZACON', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('13H00', 'CONDOR', 'PULINGUI-SILVERIA', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('13H05', 'CONDOR', 'SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('13H20', 'CONDOR', 'SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('13H30', 'CONDOR', 'PULINGUI-SILVERIA', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('13H35', 'CONDOR', 'SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('13H50', 'CONDOR', 'SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('14H00', 'CONDOR', 'PULINGUI-SILVERIA', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('14H00', 'CONDOR', 'SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('14H00', 'CONDOR', 'UCHANCHI', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('14H30', 'CONDOR', 'SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('14H45', 'CONDOR', 'SANTA LUCIA', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('15H00', 'CONDOR', 'SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('15H00', 'CONDOR', 'TAMBOHUASHA', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('15H30', 'CONDOR', 'PULINGUI-SILVERIA', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('15H30', 'CONDOR', 'SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('16H00', 'CONDOR', 'SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('16H20', 'CONDOR', 'PULINGUI-SILVERIA', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('16H30', 'CONDOR', 'SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('17H00', 'CONDOR', 'PULINGUI-SILVERIA', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('17H00', 'CONDOR', 'SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('17H10', 'CONDOR', 'SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('17H15', 'CONDOR', 'PULINGUI-SILVERIA', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('17H20', 'CONDOR', 'SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('17H30', 'CONDOR', 'PULINGUI-SILVERIA', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('17H30', 'CONDOR', 'SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('17H40', 'CONDOR', 'SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('17H45', 'CONDOR', 'PULINGUI-SILVERIA', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('17H55', 'CONDOR', 'SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('18H00', 'CONDOR', 'PULINGUI-SILVERIA', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('18H10', 'CONDOR', 'SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('18H15', 'CONDOR', 'PULINGUI-SILVERIA', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('18H25', 'CONDOR', 'SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('18H30', 'CONDOR', 'PULINGUI-SILVERIA', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('18H30', 'CONDOR', 'UCHANCHI', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('18H40', 'CONDOR', 'SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('18H45', 'CONDOR', 'PULINGUI-SILVERIA', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('19H00', 'CONDOR', 'SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('19H10', 'CONDOR', 'PULINGUI-SILVERIA', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('19H30', 'CONDOR', 'PULINGUI-SILVERIA', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('19H30', 'CONDOR', 'SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('20H00', 'CONDOR', 'SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('20H30', 'CONDOR', 'SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('21H00', 'CONDOR', 'SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('21H30', 'CONDOR', 'SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL', 'TARDE');

INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('05H50', 'ÑUCA LLACTA', 'COLUMBE', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('06H40', 'ÑUCA LLACTA', 'COLUMBE', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('07H20', 'ÑUCA LLACTA', 'COLUMBE', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('07H40', 'ÑUCA LLACTA', 'COLUMBE-CASTUG ALTO', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('08H00', 'ÑUCA LLACTA', 'COLUMBE', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('08H20', 'ÑUCA LLACTA', 'COLUMBE', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('08H40', 'ÑUCA LLACTA', 'COLUMBE', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('09H20', 'ÑUCA LLACTA', 'COLUMBE', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('09H40', 'ÑUCA LLACTA', 'COLUMBE', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('10H00', 'ÑUCA LLACTA', 'COLUMBE', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('10H20', 'ÑUCA LLACTA', 'COLUMBE', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('10H40', 'ÑUCA LLACTA', 'COLUMBE', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('11H20', 'ÑUCA LLACTA', 'COLUMBE', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('11H40', 'ÑUCA LLACTA', 'COLUMBE', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('12H00', 'ÑUCA LLACTA', 'COLUMBE', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('12H20', 'ÑUCA LLACTA', 'COLUMBE', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('12H40', 'ÑUCA LLACTA', 'COLUMBE', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('13H20', 'ÑUCA LLACTA', 'COLUMBE', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('13H40', 'ÑUCA LLACTA', 'COLUMBE', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('14H20', 'ÑUCA LLACTA', 'COLUMBE', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('14H40', 'ÑUCA LLACTA', 'COLUMBE', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('15H20', 'ÑUCA LLACTA', 'COLUMBE', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('15H40', 'ÑUCA LLACTA', 'COLUMBE', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('16H20', 'ÑUCA LLACTA', 'COLUMBE', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('16H40', 'ÑUCA LLACTA', 'COLUMBE', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('17H00', 'ÑUCA LLACTA', 'SASAPUD', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('17H20', 'ÑUCA LLACTA', 'COLUMBE', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('17H40', 'ÑUCA LLACTA', 'COLUMBE', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('18H00', 'ÑUCA LLACTA', 'COLUMBE', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('18H20', 'ÑUCA LLACTA', 'COLUMBE', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('18H40', 'ÑUCA LLACTA', 'COLUMBE', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('19H00', 'ÑUCA LLACTA', 'COLUMBE', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('19H20', 'ÑUCA LLACTA', 'COLUMBE', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('19H40', 'ÑUCA LLACTA', 'COLUMBE', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('20H00', 'ÑUCA LLACTA', 'COLUMBE', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('20H20', 'ÑUCA LLACTA', 'COLUMBE', 'TARDE');

INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('06H00', 'SAN ANDRES', 'BALSAYAN-GUANO', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('06H30', 'SAN ANDRES', 'LAS MINAS', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('06H35', 'SAN ANDRES', 'STA ROSA CHUQUIPOGLLO', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('06H45', 'SAN ANDRES', 'SAN ANDRES', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('07H00', 'SAN ANDRES', 'SAN ANDRES', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('07H05', 'SAN ANDRES', 'TAGUALAG', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('07H15', 'SAN ANDRES', 'LAS MINAS', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('07H30', 'SAN ANDRES', 'SAN ANDRES', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('07H45', 'SAN ANDRES', 'LAS MINAS', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('08H00', 'SAN ANDRES', 'SAN ANDRES', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('08H10', 'SAN ANDRES', 'EL QUINUAL', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('08H30', 'SAN ANDRES', 'SAN ANDRES', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('09H00', 'SAN ANDRES', 'SAN ANDRES', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('09H30', 'SAN ANDRES', 'SAN ANDRES', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('09H45', 'SAN ANDRES', 'LAS MINAS', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('10H00', 'SAN ANDRES', 'SAN ANDRES', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('10H15', 'SAN ANDRES', 'LAS MINAS', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('10H30', 'SAN ANDRES', 'SAN ANDRES', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('11H00', 'SAN ANDRES', 'SAN ANDRES', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('11H15', 'SAN ANDRES', 'LAS MINAS', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('11H30', 'SAN ANDRES', 'SAN ANDRES', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('12H00', 'SAN ANDRES', 'LAS MINAS', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('12H30', 'SAN ANDRES', 'SAN ANDRES', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('12H45', 'SAN ANDRES', 'SAN ANDRES', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('13H00', 'SAN ANDRES', 'SAN ANDRES', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('13H05', 'SAN ANDRES', 'LAS MINAS', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('13H15', 'SAN ANDRES', 'TAHUALAG', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('13H30', 'SAN ANDRES', 'BALSAYAN-GUANO', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('13H30', 'SAN ANDRES', 'SAN ANDRES', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('13H40', 'SAN ANDRES', 'CALSH SAN FRANCISCO', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('13H45', 'SAN ANDRES', 'SAN ANDRES', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('14H00', 'SAN ANDRES', 'SAN ANDRES', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('14H30', 'SAN ANDRES', 'SAN ANDRES', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('15H00', 'SAN ANDRES', 'SAN ANDRES', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('15H30', 'SAN ANDRES', 'SAN ANDRES', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('16H00', 'SAN ANDRES', 'SAN ANDRES', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('16H30', 'SAN ANDRES', 'SAN ANDRES', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('16H40', 'SAN ANDRES', 'STA ROSA CHUQUIPOGLLO', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('17H00', 'SAN ANDRES', 'SAN ANDRES', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('17H30', 'SAN ANDRES', 'SAN ANDRES', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('17H40', 'SAN ANDRES', 'LA JOSEFINA', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('17H45', 'SAN ANDRES', 'LAS MINAS', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('18H00', 'SAN ANDRES', 'BALSAYAN', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('18H15', 'SAN ANDRES', 'LAS MINAS', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('18H30', 'SAN ANDRES', 'SAN ANDRES', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('18H45', 'SAN ANDRES', 'LAS MINAS', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('19H10', 'SAN ANDRES', 'LAS MINAS', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('19H30', 'SAN ANDRES', 'SAN ANDRES', 'TARDE');

INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('04H30', 'SAN ISIDRO', 'PALLATANGA', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('05H30', 'SAN ISIDRO', 'PALLATANGA', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('06H40', 'SAN ISIDRO', 'CHOCAVI', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('06H45', 'SAN ISIDRO', 'SAN ISIDRO', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('07H00', 'SAN ISIDRO', 'TUTUPALA', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('07H10', 'SAN ISIDRO', 'SAN ISIDRO', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('07H20', 'SAN ISIDRO', 'SAN ISIDRO', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('08H15', 'SAN ISIDRO', 'SAN ISIDRO', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('08H45', 'SAN ISIDRO', 'SAN ISIDRO', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('09H00', 'SAN ISIDRO', 'SAN ISIDRO', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('09H15', 'SAN ISIDRO', 'CHOCAVI', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('09H20', 'SAN ISIDRO', 'SAN ISIDRO', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('10H10', 'SAN ISIDRO', 'SAN ISIDRO', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('11H10', 'SAN ISIDRO', 'SAN ISIDRO', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('11H20', 'SAN ISIDRO', 'CHOCAVI', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('11H45', 'SAN ISIDRO', 'SAN ISIDRO', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('12H15', 'SAN ISIDRO', 'SAN ISIDRO', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('12H50', 'SAN ISIDRO', 'SAN ISIDRO', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('13H00', 'SAN ISIDRO', 'TUTUPALA', 'MAÑANA');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('13H10', 'SAN ISIDRO', 'SAN ISIDRO', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('13H20', 'SAN ISIDRO', 'CHOCAVI', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('13H50', 'SAN ISIDRO', 'SAN ISIDRO', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('14H10', 'SAN ISIDRO', 'SAN ISIDRO', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('14H20', 'SAN ISIDRO', 'CHOCAVI', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('15H10', 'SAN ISIDRO', 'SAN ISIDRO', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('15H15', 'SAN ISIDRO', 'CHOCAVI', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('16H15', 'SAN ISIDRO', 'SAN ISIDRO', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('16H30', 'SAN ISIDRO', 'PALLATANGA', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('16H50', 'SAN ISIDRO', 'SAN ISIDRO', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('17H10', 'SAN ISIDRO', 'SAN ISIDRO', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('17H30', 'SAN ISIDRO', 'TUTUPALA', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('17H35', 'SAN ISIDRO', 'CHOCAVI', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('17H50', 'SAN ISIDRO', 'PULUG', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('17H55', 'SAN ISIDRO', 'SAN ISIDRO', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('18H20', 'SAN ISIDRO', 'CHOCAVI', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('18H20', 'SAN ISIDRO', 'SAN ISIDRO', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('18H45', 'SAN ISIDRO', 'SAN ISIDRO', 'TARDE');
INSERT INTO FRECUENCIAS (HORA, COOPERATIVA, DESTINO, JORNADA) VALUES ('19H20', 'SAN ISIDRO', 'SAN ISIDRO', 'TARDE');

INSERT INTO "REGISTRO" VALUES ('ALIANZA SAN JUAN','0604844324','LA CALERA','20H00','2024-10-31','45',15,'NORMAL','0.50');
INSERT INTO "REGISTRO" VALUES ('SAN ISIDRO','0604844324','SAN ISIDRO','17H10','2024-11-01','50',0,'NORMAL','0.50');
INSERT INTO "REGISTRO" VALUES ('SAN ISIDRO','0604844324','SAN ISIDRO','07H10','2024-11-01','10',0,'NORMAL','0.00');
INSERT INTO "REGISTRO" VALUES ('SAN ISIDRO','0604844324','SAN ISIDRO','07H10','2024-11-02','4',0,'NORMAL','0.50');
INSERT INTO "REGISTRO" VALUES ('ALIANZA SAN JUAN','0604844324','LA CALERA','20H00','2024-11-02','45',15,'NORMAL','0.50');
INSERT INTO "REGISTRO" VALUES ('ALIANZA SAN JUAN','0604844324','LA CALERA','06H45','2024-11-02','45',15,'NORMAL','0.50');

INSERT INTO "REGISTRO_EXTRA" VALUES ('SAN ISIDRO','0604844324','CHAMBO','19H20','2024-10-31','45',20,'EXTRA','1.00');
INSERT INTO "REGISTRO_EXTRA" VALUES ('2 DE OCTUBRE','0604844324','CHAMBO','13H50','2024-11-01','50',4,'EXTRA','1.00');
INSERT INTO "REGISTRO_EXTRA" VALUES ('SAN ISIDRO','0604844324','CHAMBO','07H10','2024-10-31','45',20,'EXTRA','1.00');
INSERT INTO "REGISTRO_EXTRA" VALUES ('SAN ISIDRO','0604844324','CHAMBO','07H10','2024-10-30','45',20,'EXTRA','1.00');
