BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "CUMPLIMIENTO" (
	"ID"	INTEGER,
	"COOPERATIVA"	TEXT,
	"SEMANAL"	INTEGER,
	"DIARIO"	INTEGER,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "FRECUENCIAS" (
	"COOPERATIVA"	TEXT,
	"DESTINO"	TEXT,
	"HORA"	TEXT,
	"JORNADA"	TEXT,
	PRIMARY KEY("COOPERATIVA","DESTINO","HORA")
);
CREATE TABLE IF NOT EXISTS "REGISTRO" (
	"COOPERATIVA"	TEXT,
	"USUARIO"	TEXT,
	"DESTINO"	TEXT,
	"HORA"	TEXT,
	"FECHA"	TEXT NOT NULL,
	"FRECUENCIA"	TEXT,
	"NUM_PASAJEROS"	INTEGER,
	"TIPO_FREC"	TEXT,
	"VALOR"	INTEGER,
	"NUM_TICKET"	TEXT,
	PRIMARY KEY("COOPERATIVA","HORA","FECHA","USUARIO","NUM_TICKET"),
	FOREIGN KEY("COOPERATIVA","DESTINO","HORA") REFERENCES "FRECUENCIAS"("COOPERATIVA","DESTINO","HORA"),
	FOREIGN KEY("USUARIO") REFERENCES "USUARIOS"("CEDULA")
);
CREATE TABLE IF NOT EXISTS "REGISTRO_EXTRA" (
	"COOPERATIVA"	TEXT,
	"USUARIO"	TEXT,
	"DESTINO"	TEXT,
	"HORA"	TEXT,
	"FECHA"	TEXT NOT NULL,
	"FRECUENCIA"	TEXT,
	"NUM_PASAJEROS"	INTEGER,
	"TIPO_FREC"	TEXT,
	"VALOR"	INTEGER,
	"NUM_TICKET"	TEXT,
	PRIMARY KEY("COOPERATIVA","HORA","FECHA","USUARIO","NUM_TICKET"),
	FOREIGN KEY("USUARIO") REFERENCES "USUARIOS"("CEDULA")
);
CREATE TABLE IF NOT EXISTS "USUARIOS" (
	"CEDULA"	TEXT,
	"NOMBRE"	TEXT NOT NULL,
	"NUMERO_CELULAR"	TEXT,
	"CONTRASEÑA"	TEXT,
	"ROL"	TEXT,
	"ESTADO"	TEXT,
	PRIMARY KEY("CEDULA")
);
INSERT INTO "CUMPLIMIENTO" VALUES (1,'2 DE OCTUBRE',217,31);
INSERT INTO "CUMPLIMIENTO" VALUES (2,'ALIANZA SAN JUAN',217,31);
INSERT INTO "CUMPLIMIENTO" VALUES (3,'CAMPESINOS UNIDOS',371,53);
INSERT INTO "CUMPLIMIENTO" VALUES (4,'CONDOR',518,74);
INSERT INTO "CUMPLIMIENTO" VALUES (5,'ÑUCA LLACTA',252,36);
INSERT INTO "CUMPLIMIENTO" VALUES (6,'SAN ANDRES',336,48);
INSERT INTO "CUMPLIMIENTO" VALUES (7,'SAN ISIDRO',266,38);
INSERT INTO "CUMPLIMIENTO" VALUES (8,'ZULA OZOGOCHE',105,15);
INSERT INTO "FRECUENCIAS" VALUES ('2 DE OCTUBRE','SAN JUAN - LA DELICIA','06H30','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('2 DE OCTUBRE','SHOBOL','06H40','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('2 DE OCTUBRE','SAN JUAN - POLVORIN','06H50','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('2 DE OCTUBRE','SAN JUAN - POLVORIN','07H15','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('2 DE OCTUBRE','U.E. CHIMBORAZO','07H45','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('2 DE OCTUBRE','POLVORIN','08H15','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('2 DE OCTUBRE','SHOBOL','08H45','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('2 DE OCTUBRE','SAN JUAN - LA DELICIA','09H15','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('2 DE OCTUBRE','SHOBOL','09H45','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('2 DE OCTUBRE','POLVORIN','10H15','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('2 DE OCTUBRE','POLVORIN','10H45','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('2 DE OCTUBRE','POLVORIN','11H15','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('2 DE OCTUBRE','POLVORIN','11H45','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('2 DE OCTUBRE','POLVORIN','12H15','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('2 DE OCTUBRE','POLVORIN','12H45','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('2 DE OCTUBRE','POLVORIN','13H10','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('2 DE OCTUBRE','POLVORIN','13H30','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('2 DE OCTUBRE','POLVORIN','13H50','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('2 DE OCTUBRE','POLVORIN','14H15','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('2 DE OCTUBRE','POLVORIN','14H45','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('2 DE OCTUBRE','POLVORIN','15H15','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('2 DE OCTUBRE','POLVORIN','15H45','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('2 DE OCTUBRE','POLVORIN','16H15','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('2 DE OCTUBRE','POLVORIN','16H45','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('2 DE OCTUBRE','POLVORIN','17H15','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('2 DE OCTUBRE','POLVORIN','17H45','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('2 DE OCTUBRE','POLVORIN','18H15','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('2 DE OCTUBRE','POLVORIN','18H45','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('2 DE OCTUBRE','POLVORIN','19H15','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('2 DE OCTUBRE','POLVORIN','19H45','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('2 DE OCTUBRE','POLVORIN','20H15','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ALIANZA SAN JUAN','GALLO RUMI','06H30','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('ALIANZA SAN JUAN','LA CALERA','06H35','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('ALIANZA SAN JUAN','LA CALERA','06H45','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('ALIANZA SAN JUAN','SAN JUAN - LA CALERA','07H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('ALIANZA SAN JUAN','SAN JUAN - LA CALERA','07H30','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('ALIANZA SAN JUAN','SAN JUAN - LA CALERA','08H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('ALIANZA SAN JUAN','LA CALERA','08H30','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('ALIANZA SAN JUAN','LA CALERA','09H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('ALIANZA SAN JUAN','LA CALERA','09H30','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('ALIANZA SAN JUAN','SAN JUAN - LA CALERA','10H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('ALIANZA SAN JUAN','SAN JUAN - LA CALERA','10H30','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('ALIANZA SAN JUAN','SAN JUAN - LA CALERA','11H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('ALIANZA SAN JUAN','LA CALERA','11H30','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('ALIANZA SAN JUAN','SAN JUAN - LA CALERA','12H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('ALIANZA SAN JUAN','SAN JUAN - LA CALERA','12H30','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('ALIANZA SAN JUAN','SAN JUAN - LA CALERA','13H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('ALIANZA SAN JUAN','LA CALERA','13H20','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ALIANZA SAN JUAN','SAN JUAN - LA CALERA','13H40','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ALIANZA SAN JUAN','SAN JUAN - LA CALERA','14H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ALIANZA SAN JUAN','SAN JUAN - LA CALERA','14H30','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ALIANZA SAN JUAN','SAN JUAN - LA CALERA','15H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ALIANZA SAN JUAN','SAN JUAN - LA CALERA','15H30','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ALIANZA SAN JUAN','SAN JUAN - LA CALERA','16H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ALIANZA SAN JUAN','SAN JUAN - LA CALERA','16H30','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ALIANZA SAN JUAN','SAN JUAN - LA CALERA','17H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ALIANZA SAN JUAN','SAN JUAN - LA CALERA','17H30','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ALIANZA SAN JUAN','SAN JUAN - LA CALERA','18H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ALIANZA SAN JUAN','SAN JUAN - LA CALERA','18H30','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ALIANZA SAN JUAN','SAN JUAN - LA CALERA','19H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ALIANZA SAN JUAN','SAN JUAN - LA CALERA','19H30','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ALIANZA SAN JUAN','LA CALERA','20H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','CALPILOMA','13H30','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','LA MOYA-JATARI-RUMICRUZ','13H30','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','PALACIO REAL','13H30','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','CHIQUICAZ','14H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','LA MOYA-JATARI-RUMICRUZ','14H10','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','CUNDUANA-GAUSHI CHICO','15H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','NITILUISA','15H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','SAN FRANCISCO DE CUNUGUACHAY','15H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','LA MOYA-JATARI-RUMICRUZ','16H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','NITILUISA','16H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','LA MOYA-JATARI-RUMICRUZ','16H30','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','NITILUISA','17H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','SAN FRANCISCO DE CUNUGUACHAY','17H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','LA MOYA-JATARI-RUMICRUZ','17H30','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','PALACIO REAL','17H30','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','CALPILOMA','18H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','CUNDUANA-GAUSHI CHICO','18H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','LA MOYA-JATARI-RUMICRUZ','18H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','NITILUISA','18H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','CHIQUICAZ','18H30','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','LA MOYA-JATARI-RUMICRUZ','18H30','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','LA MOYA-JATARI-RUMICRUZ','18H45','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','LA MOYA-JATARI-RUMICRUZ','19H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','NITILUISA','19H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','LA MOYA-JATARI-RUMICRUZ','19H15','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','LA MOYA-JATARI-RUMICRUZ','19H25','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','LA MOYA-JATARI-RUMICRUZ','06H45','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','CHIQUICAZ','07H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','CUNDUANA-GAUSHI CHICO','07H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','LA MOYA-JATARI-RUMICRUZ','07H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','NITILUISA','07H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','SAN FRANCISCO DE CUNUGUACHAY','07H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','LA MOYA-JATARI-RUMICRUZ','07H15','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','CALPILOMA','07H30','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','LA MOYA-JATARI-RUMICRUZ','07H30','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','PALACIO REAL','07H30','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','SAN FRANCISCO DE CUNUGUACHAY','07H30','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','LA MOYA-JATARI-RUMICRUZ','08H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','NITILUISA','08H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','LA MOYA-JATARI-RUMICRUZ','09H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','LA MOYA-JATARI-RUMICRUZ','10H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','LA MOYA-JATARI-RUMICRUZ','10H35','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','CALPILOMA','11H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','CHIQUICAZ','11H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','LA MOYA-JATARI-RUMICRUZ','11H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','PALACIO REAL','11H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','SAN FRANCISCO DE CUNUGUACHAY','11H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','NITILUISA','11H30','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','CUNDUANA-GAUSHI CHICO','12H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','LA MOYA-JATARI-RUMICRUZ','12H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','NITILUISA','12H30','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','SAN FRANCISCO DE CUNUGUACHAY','12H30','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CAMPESINOS UNIDOS','LA MOYA-JATARI-RUMICRUZ','13H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL','06H20','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','PULINGUI-SILVERIA','06H30','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL','06H30','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SANJAPAMBA','06H40','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL','06H45','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','BATZACON','06H50','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','PULINGUI-SILVERIA','06H50','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','BATZACON','07H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SANTA LUCIA','07H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL','07H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','UCHANCHI','07H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','PULINGUI-SILVERIA','07H30','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL','07H30','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL','08H10','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','PULINGUI-SILVERIA','08H30','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL','08H50','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','PULINGUI-SILVERIA','09H30','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL','09H30','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL','10H10','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SANJAPAMBA','10H15','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL','10H50','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SANTA LUCIA','11H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL','11H20','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','PULINGUI-SILVERIA','11H45','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL','11H50','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','UCHANCHI','12H10','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL','12H20','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','PULINGUI-SILVERIA','12H30','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL','12H50','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','BATZACON','13H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','PULINGUI-SILVERIA','13H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL','13H05','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL','13H20','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','PULINGUI-SILVERIA','13H30','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL','13H35','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL','13H50','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','PULINGUI-SILVERIA','14H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL','14H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','UCHANCHI','14H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL','14H30','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SANTA LUCIA','14H45','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL','15H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','TAMBOHUASHA','15H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','PULINGUI-SILVERIA','15H30','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL','15H30','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL','16H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','PULINGUI-SILVERIA','16H20','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL','16H30','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','PULINGUI-SILVERIA','17H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL','17H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL','17H10','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','PULINGUI-SILVERIA','17H15','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL','17H20','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','PULINGUI-SILVERIA','17H30','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL','17H30','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL','17H40','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','PULINGUI-SILVERIA','17H45','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL','17H55','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','PULINGUI-SILVERIA','18H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL','18H10','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','PULINGUI-SILVERIA','18H15','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL','18H25','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','PULINGUI-SILVERIA','18H30','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','UCHANCHI','18H30','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL','18H40','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','PULINGUI-SILVERIA','18H45','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL','19H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','PULINGUI-SILVERIA','19H10','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','PULINGUI-SILVERIA','19H30','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL','19H30','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL','20H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL','20H30','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL','21H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('CONDOR','SIGSIPAMBA-BATZACON-LATURUN-SAN RAFAEL','21H30','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ÑUCA LLACTA','COLUMBE','05H50','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('ÑUCA LLACTA','COLUMBE','06H40','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('ÑUCA LLACTA','COLUMBE','07H20','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('ÑUCA LLACTA','COLUMBE-CASTUG ALTO','07H40','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('ÑUCA LLACTA','COLUMBE','08H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('ÑUCA LLACTA','COLUMBE','08H20','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('ÑUCA LLACTA','COLUMBE','08H40','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('ÑUCA LLACTA','COLUMBE','09H20','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('ÑUCA LLACTA','COLUMBE','09H40','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('ÑUCA LLACTA','COLUMBE','10H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('ÑUCA LLACTA','COLUMBE','10H20','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('ÑUCA LLACTA','COLUMBE','10H40','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('ÑUCA LLACTA','COLUMBE','11H20','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('ÑUCA LLACTA','COLUMBE','11H40','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('ÑUCA LLACTA','COLUMBE','12H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('ÑUCA LLACTA','COLUMBE','12H20','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('ÑUCA LLACTA','COLUMBE','12H40','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('ÑUCA LLACTA','COLUMBE','13H20','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ÑUCA LLACTA','COLUMBE','13H40','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ÑUCA LLACTA','COLUMBE','14H20','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ÑUCA LLACTA','COLUMBE','14H40','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ÑUCA LLACTA','COLUMBE','15H20','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ÑUCA LLACTA','COLUMBE','15H40','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ÑUCA LLACTA','COLUMBE','16H20','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ÑUCA LLACTA','COLUMBE','16H40','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ÑUCA LLACTA','SASAPUD','17H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ÑUCA LLACTA','COLUMBE','17H20','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ÑUCA LLACTA','COLUMBE','17H40','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ÑUCA LLACTA','COLUMBE','18H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ÑUCA LLACTA','COLUMBE','18H20','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ÑUCA LLACTA','COLUMBE','18H40','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ÑUCA LLACTA','COLUMBE','19H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ÑUCA LLACTA','COLUMBE','19H20','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ÑUCA LLACTA','COLUMBE','19H40','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ÑUCA LLACTA','COLUMBE','20H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ÑUCA LLACTA','COLUMBE','20H20','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','BALSAYAN-GUANO','06H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','LAS MINAS','06H30','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','STA ROSA CHUQUIPOGLLO','06H35','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','SAN ANDRES','06H45','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','SAN ANDRES','07H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','TAGUALAG','07H05','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','LAS MINAS','07H15','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','SAN ANDRES','07H30','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','LAS MINAS','07H45','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','SAN ANDRES','08H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','EL QUINUAL','08H10','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','SAN ANDRES','08H30','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','SAN ANDRES','09H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','SAN ANDRES','09H30','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','LAS MINAS','09H45','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','SAN ANDRES','10H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','LAS MINAS','10H15','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','SAN ANDRES','10H30','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','SAN ANDRES','11H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','LAS MINAS','11H15','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','SAN ANDRES','11H30','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','LAS MINAS','12H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','SAN ANDRES','12H30','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','SAN ANDRES','12H45','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','SAN ANDRES','13H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','LAS MINAS','13H05','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','TAHUALAG','13H15','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','BALSAYAN-GUANO','13H30','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','SAN ANDRES','13H30','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','CALSH SAN FRANCISCO','13H40','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','SAN ANDRES','13H45','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','SAN ANDRES','14H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','SAN ANDRES','14H30','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','SAN ANDRES','15H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','SAN ANDRES','15H30','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','SAN ANDRES','16H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','SAN ANDRES','16H30','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','STA ROSA CHUQUIPOGLLO','16H40','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','SAN ANDRES','17H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','SAN ANDRES','17H30','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','LA JOSEFINA','17H40','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','LAS MINAS','17H45','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','BALSAYAN','18H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','LAS MINAS','18H15','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','SAN ANDRES','18H30','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','LAS MINAS','18H45','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','LAS MINAS','19H10','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ANDRES','SAN ANDRES','19H30','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ISIDRO','PALLATANGA','04H30','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ISIDRO','PALLATANGA','05H30','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ISIDRO','CHOCAVI','06H40','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ISIDRO','SAN ISIDRO','06H45','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ISIDRO','TUTUPALA','07H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ISIDRO','SAN ISIDRO','07H10','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ISIDRO','SAN ISIDRO','07H20','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ISIDRO','SAN ISIDRO','08H15','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ISIDRO','SAN ISIDRO','08H45','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ISIDRO','SAN ISIDRO','09H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ISIDRO','CHOCAVI','09H15','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ISIDRO','SAN ISIDRO','09H20','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ISIDRO','SAN ISIDRO','10H10','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ISIDRO','SAN ISIDRO','11H10','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ISIDRO','CHOCAVI','11H20','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ISIDRO','SAN ISIDRO','11H45','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ISIDRO','SAN ISIDRO','12H15','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ISIDRO','SAN ISIDRO','12H50','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ISIDRO','TUTUPALA','13H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ISIDRO','SAN ISIDRO','13H10','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ISIDRO','CHOCAVI','13H20','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ISIDRO','SAN ISIDRO','13H50','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ISIDRO','SAN ISIDRO','14H10','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ISIDRO','CHOCAVI','14H20','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ISIDRO','SAN ISIDRO','15H10','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ISIDRO','CHOCAVI','15H15','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ISIDRO','SAN ISIDRO','16H15','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ISIDRO','PALLATANGA','16H30','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ISIDRO','SAN ISIDRO','16H50','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ISIDRO','SAN ISIDRO','17H10','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ISIDRO','TUTUPALA','17H30','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ISIDRO','CHOCAVI','17H35','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ISIDRO','PULUG','17H50','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ISIDRO','SAN ISIDRO','17H55','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ISIDRO','CHOCAVI','18H20','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ISIDRO','SAN ISIDRO','18H20','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ISIDRO','SAN ISIDRO','18H45','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('SAN ISIDRO','SAN ISIDRO','19H20','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ZULA OZOGOCHE','TOTORAS','05H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('ZULA OZOGOCHE','PACHAMAMA CHICO','05H20','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('ZULA OZOGOCHE','TOTORAS','06H30','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('ZULA OZOGOCHE','PACHAMAMA CHICO','12H00','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('ZULA OZOGOCHE','PUCATOTORAS','12H30','MAÑANA');
INSERT INTO "FRECUENCIAS" VALUES ('ZULA OZOGOCHE','TOTORAS','13H20','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ZULA OZOGOCHE','JUBAL','13H45','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ZULA OZOGOCHE','TOTORAS','14H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ZULA OZOGOCHE','SANTA ROSA DE CHICHO','14H30','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ZULA OZOGOCHE','TOTORAS','14H30','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ZULA OZOGOCHE','ALAUSI-ACHUPALLAS','14H45','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ZULA OZOGOCHE','TOTORAS','15H30','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ZULA OZOGOCHE','TOTORAS','16H00','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ZULA OZOGOCHE','ALAUSI-ACHUPALLAS','16H15','TARDE');
INSERT INTO "FRECUENCIAS" VALUES ('ZULA OZOGOCHE','TOTORAS','17H30','TARDE');
INSERT INTO "USUARIOS" VALUES ('0605888221','Joel Inca','098 305 4758','admin','superadmin','activo');
INSERT INTO "USUARIOS" VALUES ('0604844324','Cristina Huisha','098 305 4758','admin','superadmin','activo');
INSERT INTO "USUARIOS" VALUES ('06048443241','Cristina Huisha','098 305 4758','admin','usuario','activo');
INSERT INTO "USUARIOS" VALUES ('1709694788','Paúl Fernando Vásquez Dávalos','','1709694788','usuario','activo');
INSERT INTO "USUARIOS" VALUES ('0603011800','Guillermo Marcelo Endara Sánchez','','0603011800','usuario','activo');
INSERT INTO "USUARIOS" VALUES ('0103860367','Cesar Fernando Padilla Palacios','','0103860367','admin','activo');
INSERT INTO "USUARIOS" VALUES ('0603049669','Silvana Leonor Mantilla Robalino','','0603011800','secretaria','activo');
INSERT INTO "REGISTRO" VALUES ('ALIANZA SAN JUAN','0604844324','LA CALERA','20H00','2024-10-31','45',15,'NORMAL',0.5,'1');
INSERT INTO "REGISTRO" VALUES ('SAN ISIDRO','0604844324','SAN ISIDRO','17H10','2024-11-01','50',0,'NORMAL',0.5,'1');
INSERT INTO "REGISTRO" VALUES ('SAN ISIDRO','0604844324','SAN ISIDRO','07H10','2024-11-01','10',0,'NORMAL',0,'1');
INSERT INTO "REGISTRO" VALUES ('SAN ISIDRO','0604844324','SAN ISIDRO','07H10','2024-11-02','4',0,'NORMAL',0.5,'1');
INSERT INTO "REGISTRO" VALUES ('ALIANZA SAN JUAN','0604844324','LA CALERA','20H00','2024-11-02','45',15,'NORMAL',0.5,'1');
INSERT INTO "REGISTRO" VALUES ('ALIANZA SAN JUAN','0604844324','LA CALERA','06H45','2024-11-02','45',15,'NORMAL',0.5,'1');
INSERT INTO "REGISTRO_EXTRA" VALUES ('SAN ISIDRO','0604844324','CHAMBO','19H20','2024-10-31','45',20,'EXTRA',1,'1');
INSERT INTO "REGISTRO_EXTRA" VALUES ('2 DE OCTUBRE','0604844324','CHAMBO','13H50','2024-11-01','50',4,'EXTRA',1,'1');
INSERT INTO "REGISTRO_EXTRA" VALUES ('SAN ISIDRO','0604844324','CHAMBO','07H10','2024-10-31','45',20,'EXTRA',1,'1');
INSERT INTO "REGISTRO_EXTRA" VALUES ('SAN ISIDRO','0604844324','CHAMBO','07H10','2024-10-30','45',20,'EXTRA',1,'1');
COMMIT;